const CIM={lat:-3.8455,lon:-38.4596,runways:[130,310],length:230,timezone:'America/Fortaleza'};

const weatherMap={0:['☀️','Céu limpo'],1:['🌤️','Predominantemente limpo'],2:['⛅','Parcialmente nublado'],3:['☁️','Nublado'],45:['🌫️','Neblina'],48:['🌫️','Neblina com geada'],51:['🌦️','Garoa fraca'],53:['🌦️','Garoa'],55:['🌧️','Garoa forte'],61:['🌦️','Chuva fraca'],63:['🌧️','Chuva'],65:['🌧️','Chuva forte'],80:['🌦️','Pancadas fracas'],81:['🌧️','Pancadas'],82:['⛈️','Pancadas fortes'],95:['⛈️','Trovoadas'],96:['⛈️','Trovoadas com granizo'],99:['⛈️','Trovoadas fortes']};

function weather(code){return weatherMap[code]||['🌤️','Condições variáveis']}
function round(v,d=0){return Number(v).toFixed(d)}
function normalizeAngle(a){return((a%360)+360)%360}
function signedAngle(a,b){let d=normalizeAngle(a-b);if(d>180)d-=360;return d}
function formatTime(value){return new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:CIM.timezone}).format(new Date(value))}
function formatDay(value){return new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'2-digit',timeZone:CIM.timezone}).format(new Date(value+'T12:00:00-03:00')).replace('.','')}
function compass(deg){const p=['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSO','SO','OSO','O','ONO','NO','NNO'];return p[Math.round(normalizeAngle(deg)/22.5)%16]}

function updateClock(){const now=new Date();document.querySelector('#clock-time').textContent=new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:CIM.timezone}).format(now);document.querySelector('#clock-date').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',timeZone:CIM.timezone}).format(now)}

function runwayAnalysis(direction,speed){const candidates=CIM.runways.map(runway=>{const delta=signedAngle(direction,runway);const head=speed*Math.cos(delta*Math.PI/180);const cross=speed*Math.sin(delta*Math.PI/180);return{runway,delta,head,cross}});candidates.sort((a,b)=>b.head-a.head);return candidates[0]}

function evaluate(current,daily){const runway=runwayAnalysis(current.wind_direction_10m,current.wind_speed_10m);const cross=Math.abs(runway.cross);const gust=current.wind_gusts_10m||0;const rain=daily.precipitation_probability_max?.[0]||0;const vis=(current.visibility||10000)/1000;let level='good',title='Boa janela para voar',message='Condições favoráveis no momento. Faça o checklist completo e confirme a biruta antes da decolagem.';
  if(gust>35||cross>20||rain>=60||vis<4){level='bad';title='Condições desfavoráveis';message='Há fatores meteorológicos que recomendam cautela elevada ou adiamento do voo.'}
  else if(gust>25||cross>12||rain>=35||vis<8){level='caution';title='Atenção às condições';message='As condições permitem avaliação, mas vento, rajadas ou chuva exigem margem operacional maior.'}
  return{level,title,message,runway};}

function render(data){const c=data.current,d=data.daily,h=data.hourly;const [icon,desc]=weather(c.weather_code);const analysis=evaluate(c,d);const status=document.querySelector('#status-card');status.className='status-card '+analysis.level;document.querySelector('#flight-status').textContent=analysis.title;document.querySelector('#flight-message').textContent=analysis.message;document.querySelector('#temperature').textContent=`${Math.round(c.temperature_2m)}°`;document.querySelector('#weather-description').textContent=desc;document.querySelector('#weather-icon').textContent=icon;document.querySelector('#feels-like').textContent=`Sensação: ${Math.round(c.apparent_temperature)}°C`;document.querySelector('#wind-speed').textContent=Math.round(c.wind_speed_10m);document.querySelector('#wind-direction').textContent=`${Math.round(c.wind_direction_10m)}° ${compass(c.wind_direction_10m)}`;document.querySelector('#wind-gust').textContent=`${Math.round(c.wind_gusts_10m)} km/h`;document.querySelector('#wind-arrow').style.transform=`rotate(${c.wind_direction_10m+180}deg)`;

 const rw=analysis.runway;document.querySelector('#preferred-runway').textContent=`Preferência: pista ${rw.runway===130?'13':'31'}`;document.querySelector('#headwind-component').textContent=`${Math.abs(rw.head).toFixed(1)} km/h`;document.querySelector('#headwind-label').textContent=rw.head>=0?'vento de proa':'vento de cauda';document.querySelector('#crosswind-component').textContent=`${Math.abs(rw.cross).toFixed(1)} km/h`;document.querySelector('#crosswind-side').textContent=Math.abs(rw.cross)<0.5?'praticamente sem través':rw.cross>0?'da esquerda para a direita':'da direita para a esquerda';

 document.querySelector('#humidity').textContent=`${Math.round(c.relative_humidity_2m)}%`;document.querySelector('#pressure').textContent=`${Math.round(c.surface_pressure)} hPa`;document.querySelector('#visibility').textContent=`${((c.visibility||0)/1000).toFixed(1)} km`;document.querySelector('#rain-probability').textContent=`${Math.round(d.precipitation_probability_max[0]||0)}%`;document.querySelector('#uv-index').textContent=round(d.uv_index_max[0],0);document.querySelector('#sunset').textContent=formatTime(d.sunset[0]);

 const now=new Date();const hourly=[];for(let i=0;i<h.time.length&&hourly.length<10;i++){const t=new Date(h.time[i]);if(t>=now){const w=weather(h.weather_code[i]);hourly.push(`<article class="forecast-item ${hourly.length===0?'now':''}"><strong>${hourly.length===0?'Agora':formatTime(h.time[i])}</strong><span class="icon">${w[0]}</span><strong>${Math.round(h.temperature_2m[i])}°C</strong><small>Vento ${Math.round(h.wind_speed_10m[i])} km/h<br>Raj. ${Math.round(h.wind_gusts_10m[i])} km/h</small></article>`)}}document.querySelector('#hourly-forecast').innerHTML=hourly.join('');

 document.querySelector('#daily-forecast').innerHTML=d.time.map((day,i)=>{const w=weather(d.weather_code[i]);return`<article class="forecast-item"><strong>${i===0?'Hoje':formatDay(day)}</strong><span class="icon">${w[0]}</span><strong>${Math.round(d.temperature_2m_min[i])}° / ${Math.round(d.temperature_2m_max[i])}°</strong><small>Chuva ${Math.round(d.precipitation_probability_max[i]||0)}%<br>Raj. ${Math.round(d.wind_gusts_10m_max[i])} km/h</small></article>`}).join('');}

async function loadWeather(){const params=new URLSearchParams({latitude:CIM.lat,longitude:CIM.lon,timezone:CIM.timezone,forecast_days:'7',current:'temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,visibility',hourly:'temperature_2m,weather_code,wind_speed_10m,wind_gusts_10m',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,wind_speed_10m_max,wind_gusts_10m_max,uv_index_max,sunrise,sunset'});try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`);if(!r.ok)throw new Error('weather');render(await r.json())}catch(err){const s=document.querySelector('#status-card');s.className='status-card bad';document.querySelector('#flight-status').textContent='Falha ao atualizar o clima';document.querySelector('#flight-message').textContent='Não foi possível consultar os dados meteorológicos agora. Tente novamente em alguns instantes.'}}

updateClock();setInterval(updateClock,1000);loadWeather();setInterval(loadWeather,15*60*1000);
