(() => {
  'use strict';

  const W=1080,H=1350,TZ='America/Fortaleza';
  const LOGO='assets/cim-logo-oficial.webp?v=20260910-1';
  const PHOTO='assets/cim-pista-hero.webp?v=20260901-final1';
  let activeUrl='';
  const $=s=>document.querySelector(s), tx=s=>$(s)?.textContent?.trim()||'';
  const num=v=>{const m=String(v??'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):NaN};
  const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');
  const fmt=(v,s='',d=0)=>Number.isFinite(v)?`${v.toLocaleString('pt-BR',{maximumFractionDigits:d})}${s}`:'—';
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

  function cardinal(deg){if(!Number.isFinite(deg))return '—';const p=['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSO','SO','OSO','O','ONO','NO','NNO'];return p[Math.round((((deg%360)+360)%360)/22.5)%16]}
  function dateInfo(){const d=new Date(),weekday=new Intl.DateTimeFormat('pt-BR',{weekday:'long',timeZone:TZ}).format(d).toUpperCase(),parts=new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'long',year:'numeric',timeZone:TZ}).formatToParts(d),day=parts.find(p=>p.type==='day')?.value||'',month=(parts.find(p=>p.type==='month')?.value||'').toUpperCase(),year=parts.find(p=>p.type==='year')?.value||'',time=new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:TZ}).format(d);return{weekday,date:`${day} DE ${month} DE ${year}`,time}}
  function nextHours(){try{if(typeof briefingState==='undefined'||!briefingState.lastData||typeof briefingBuildHours!=='function')return[];return briefingBuildHours(briefingState.lastData,0,new Date()).hours.slice(0,4).map(h=>({time:typeof briefingHour==='function'?briefingHour(h.time):'—',wind:+h.windSpeed||0,gust:+h.gust||0,precip:+h.precip||0}))}catch(_){return[]}}
  function collect(){const dir=num(tx('#wind-direction')),raw=tx('#weather-description');return{...dateInfo(),condition:raw&&raw!=='--'?raw.charAt(0).toUpperCase()+raw.slice(1):'Condições no CIM',temp:num(tx('#temperature')),visibility:num(tx('#visibility')),rain:num(tx('#rain-probability')),rainPop:num(tx('#rain-total')),wind:num(tx('#wind-speed')),dir,gust:num(tx('#wind-gust')),cardinal:cardinal(dir),sunrise:tx('#sunrise').replace(/^Nascer\s*/i,'')||'—',sunset:tx('#sunset')||'—',hours:nextHours()}}

  function daylight(d){const hh=(v,f)=>{const m=String(v||'').match(/(\d{1,2}):(\d{2})/);return m?+m[1]+(+m[2]/60):f},rise=hh(d.sunrise,5.5),set=hh(d.sunset,17.7),now=hh(d.time,rise),x1=270,x2=830,x=x1+(x2-x1)*clamp((now-rise)/Math.max(.1,set-rise),0,1);return `<g><rect x="34" y="936" width="1012" height="110" rx="20" fill="#031a2a" fill-opacity=".92" stroke="#24aee8" stroke-opacity=".72"/><text x="540" y="966" text-anchor="middle" class="section">PERÍODO DIURNO</text><line x1="${x1}" y1="994" x2="${x2}" y2="994" stroke="#43bdf0" stroke-width="4" stroke-linecap="round"/><circle cx="${x}" cy="994" r="10" fill="#fff" stroke="#43bdf0" stroke-width="4"/><text x="82" y="990" class="sunTime">${esc(d.sunrise)}</text><text x="82" y="1019" class="sunLabel">NASCER</text><text x="998" y="990" text-anchor="end" class="sunTime">${esc(d.sunset)}</text><text x="998" y="1019" text-anchor="end" class="sunLabel">PÔR DO SOL</text><text x="${x}" y="1028" text-anchor="middle" class="now">AGORA</text></g>`}
  function hours(d){const a=d.hours.length?d.hours:[{},{},{},{}],xs=[70,310,550,790];return a.slice(0,4).map((h,i)=>`<g transform="translate(${xs[i]} 0)">${i?'<line x1="-28" y1="1122" x2="-28" y2="1248" stroke="#73b9d6" stroke-opacity=".55"/>':''}<text y="1146" class="hourTime">${esc(h.time||'—')}</text><text y="1190" class="hourWind">${fmt(h.wind)}</text><text x="72" y="1190" class="hourUnit">KM/H</text><text y="1227" class="hourDetail">RAJ. ${fmt(h.gust)} KM/H</text><text y="1260" class="hourDetail">CHUVA ${fmt(h.precip,' mm',1)}</text></g>`).join('')}

  function svg(d,logo,photo){const wind=fmt(d.wind),dir=Number.isFinite(d.dir)?`${Math.round(d.dir)}°`:'—',gust=fmt(d.gust);return `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><defs><linearGradient id="shade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#03101a" stop-opacity=".28"/><stop offset=".48" stop-color="#03101a" stop-opacity=".22"/><stop offset=".70" stop-color="#03101a" stop-opacity=".60"/><stop offset="1" stop-color="#020b12" stop-opacity=".98"/></linearGradient><filter id="shadow"><feDropShadow dx="0" dy="5" stdDeviation="8" flood-color="#000" flood-opacity=".48"/></filter><style>text{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif}.date1{fill:#fff;font-size:25px;font-weight:900}.date2{fill:#fff;font-size:20px;font-weight:850}.date3{fill:#d4e0e7;font-size:17px}.kicker{fill:#fff;font-size:22px;font-weight:800;letter-spacing:6px}.condition{fill:#fff;font-size:84px;font-weight:950;letter-spacing:-3px}.windMain{fill:#fff;font-size:150px;font-weight:950;letter-spacing:-8px}.windUnit{fill:#fff;font-size:48px;font-weight:950}.windDir{fill:#fff;font-size:33px;font-weight:900}.gust{fill:#70d0fa;font-size:30px;font-weight:950}.meta{fill:#fff;font-size:18px;font-weight:750;letter-spacing:1px}.metricV{fill:#fff;font-size:38px;font-weight:950}.metricL{fill:#fff;font-size:18px}.section{fill:#fff;font-size:17px;font-weight:750;letter-spacing:4px}.sunTime{fill:#fff;font-size:28px;font-weight:950}.sunLabel{fill:#cbd8df;font-size:17px}.now{fill:#fff;font-size:17px;font-weight:800}.hourTitle{fill:#fff;font-size:18px;font-weight:800;letter-spacing:4px}.hourTime{fill:#54c6f6;font-size:28px;font-weight:950}.hourWind{fill:#fff;font-size:36px;font-weight:950}.hourUnit{fill:#fff;font-size:18px;font-weight:900}.hourDetail{fill:#fff;font-size:18px}.footer{fill:#d7e3e9;font-size:14px;font-weight:600}</style></defs><image href="${photo}" x="0" y="0" width="1080" height="1350" preserveAspectRatio="xMidYMid slice"/><rect width="1080" height="1350" fill="url(#shade)"/><rect x="0" y="755" width="1080" height="595" fill="#02111c" fill-opacity=".73"/>
  <g filter="url(#shadow)"><rect x="50" y="50" width="345" height="138" rx="24" fill="#fff"/><image href="${logo}" x="66" y="62" width="313" height="114" preserveAspectRatio="xMidYMid meet"/></g>
  <g transform="translate(750 58)"><rect width="280" height="132" rx="18" fill="#04192a" fill-opacity=".80"/><text x="250" y="36" text-anchor="end" class="date1">${esc(d.weekday)}</text><text x="250" y="70" text-anchor="end" class="date2">${esc(d.date)}</text><line x1="42" y1="86" x2="250" y2="86" stroke="#d7e3e9" stroke-opacity=".6"/><text x="250" y="114" text-anchor="end" class="date3">ATUALIZAÇÃO: ${esc(d.time)} (BT)</text></g>
  <text x="64" y="255" class="kicker">CONDIÇÕES AGORA</text><line x1="64" y1="278" x2="162" y2="278" stroke="#39c4f6" stroke-width="6" stroke-linecap="round"/><text x="64" y="365" class="condition">${esc(d.condition)}</text>
  <g transform="translate(64 438)" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round"><path d="M0 18H60c22 0 22-30 2-30-9 0-16 5-19 12"/><path d="M0 48H78c19 0 19 28 2 28-9 0-15-5-18-11"/><path d="M0 76H48"/></g><text x="178" y="542" class="windMain">${wind}</text><text x="392" y="542" class="windUnit">KM/H</text><text x="178" y="590" class="windDir">${dir} · VENTO DE ${esc(d.cardinal)}</text><line x1="178" y1="612" x2="455" y2="612" stroke="#fff" stroke-opacity=".55"/><text x="178" y="650" class="gust">RAJADA ${gust} KM/H</text><text x="64" y="698" class="meta">CIM · EUSÉBIO · PISTA 13/31 · 230 × 12 M</text>
  <g><rect x="34" y="796" width="1012" height="128" rx="20" fill="#031a2a" fill-opacity=".93" stroke="#24aee8" stroke-opacity=".72"/><line x1="292" y1="822" x2="292" y2="900" stroke="#6fb9d8" stroke-opacity=".65"/><line x1="545" y1="822" x2="545" y2="900" stroke="#6fb9d8" stroke-opacity=".65"/><line x1="790" y1="822" x2="790" y2="900" stroke="#6fb9d8" stroke-opacity=".65"/><text x="70" y="850" class="metricV">${fmt(d.temp,'°')}</text><text x="70" y="884" class="metricL">Temperatura</text><text x="330" y="850" class="metricV">${fmt(d.rain,' mm',1)}</text><text x="330" y="884" class="metricL">Chuva</text><text x="580" y="850" class="metricV">${fmt(d.rainPop,'%')}</text><text x="580" y="884" class="metricL">Próxima hora</text><text x="825" y="850" class="metricV">${fmt(d.visibility,' km')}</text><text x="825" y="884" class="metricL">Visibilidade</text></g>
  ${daylight(d)}<g><rect x="34" y="1058" width="1012" height="226" rx="20" fill="#031a2a" fill-opacity=".94" stroke="#24aee8" stroke-opacity=".72"/><text x="64" y="1094" class="hourTitle">PRÓXIMAS HORAS</text><line x1="64" y1="1110" x2="178" y2="1110" stroke="#39c4f6" stroke-width="5" stroke-linecap="round"/>${hours(d)}</g><line x1="160" y1="1316" x2="260" y2="1316" stroke="#d7e3e9" stroke-opacity=".7"/><text x="540" y="1323" text-anchor="middle" class="footer">MODELO NAS COORDENADAS DO CIM · METAR SBFZ É REFERÊNCIA REGIONAL</text><line x1="820" y1="1316" x2="920" y2="1316" stroke="#d7e3e9" stroke-opacity=".7"/></svg>`}

  async function dataUrl(src){const r=await fetch(src,{cache:'no-store'});if(!r.ok)throw new Error(`asset ${r.status}`);const b=await r.blob();return await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(b)})}
  async function toPng(markup){const u=URL.createObjectURL(new Blob([markup],{type:'image/svg+xml;charset=utf-8'}));try{const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=u});const c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,W,H);return await new Promise(res=>c.toBlob(res,'image/png',.96))}finally{URL.revokeObjectURL(u)}}
  function ensureUi(){if($('#cim-briefing-overlay'))return;const st=document.createElement('style');st.textContent='.cim-briefing-overlay{position:fixed;inset:0;background:rgba(1,7,11,.94);backdrop-filter:blur(18px);z-index:9999;display:none;align-items:center;justify-content:center;padding:20px}.cim-briefing-overlay.open{display:flex}.cim-briefing-shell{width:min(94vw,620px);max-height:95vh;display:flex;flex-direction:column;gap:14px}.cim-briefing-preview{background:#020b12;border:1px solid rgba(101,207,247,.28);border-radius:22px;overflow:auto;box-shadow:0 28px 90px rgba(0,0,0,.5)}.cim-briefing-preview img{display:block;width:100%;height:auto}.cim-briefing-actions{display:flex;gap:10px;justify-content:flex-end;flex-wrap:wrap}.cim-briefing-actions button{border:0;border-radius:999px;padding:12px 18px;font:700 14px system-ui;cursor:pointer}.cim-briefing-primary{background:#65cff7;color:#02111b}.cim-briefing-secondary{background:#173042;color:#e8f5fb}@media(max-width:600px){.cim-briefing-overlay{padding:10px}.cim-briefing-shell{width:100%;max-height:98vh}.cim-briefing-actions{justify-content:stretch}.cim-briefing-actions button{flex:1}}';document.head.appendChild(st);const o=document.createElement('div');o.id='cim-briefing-overlay';o.className='cim-briefing-overlay';o.innerHTML='<div class="cim-briefing-shell" role="dialog" aria-modal="true" aria-label="Prévia do briefing visual do CIM"><div class="cim-briefing-preview"><img id="cim-briefing-preview-image" alt="Condições meteorológicas atuais do CIM"></div><div class="cim-briefing-actions"><button id="cim-briefing-close" class="cim-briefing-secondary">Fechar</button><button id="cim-briefing-save" class="cim-briefing-secondary">Salvar PNG</button><button id="cim-briefing-share" class="cim-briefing-primary">Compartilhar</button></div></div>';document.body.appendChild(o);$('#cim-briefing-close').onclick=()=>o.classList.remove('open');o.onclick=e=>{if(e.target===o)o.classList.remove('open')}}
  async function show(){const b=$('#today-cim-briefing-visual'),old=b?.textContent||'Gerar briefing visual';if(b){b.disabled=true;b.textContent='Gerando briefing…'}try{const d=collect();if(!Number.isFinite(d.wind)||!Number.isFinite(d.dir)||!Number.isFinite(d.temp))throw new Error('dados ainda não carregados');const [logo,photo]=await Promise.all([dataUrl(LOGO),dataUrl(PHOTO)]),blob=await toPng(svg(d,logo,photo));if(!blob)throw new Error('PNG vazio');if(activeUrl)URL.revokeObjectURL(activeUrl);activeUrl=URL.createObjectURL(blob);const file=new File([blob],`cim-condicoes-${new Intl.DateTimeFormat('en-CA',{timeZone:TZ}).format(new Date())}.png`,{type:'image/png'});ensureUi();$('#cim-briefing-preview-image').src=activeUrl;$('#cim-briefing-overlay').classList.add('open');$('#cim-briefing-share').onclick=async()=>{if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'Condições agora · CIM'});else{const a=document.createElement('a');a.href=activeUrl;a.download=file.name;a.click()}};$('#cim-briefing-save').onclick=()=>{const a=document.createElement('a');a.href=activeUrl;a.download=file.name;a.click()}}catch(e){console.error('[Briefing visual CIM]',e);alert('Não foi possível gerar o briefing visual agora. Aguarde os dados do painel e tente novamente.')}finally{if(b){b.disabled=false;b.textContent=old}}}
  function install(){const share=$('#today-cim-share');if(!share||$('#today-cim-briefing-visual'))return;const b=document.createElement('button');b.id='today-cim-briefing-visual';b.className='today-cim-share';b.type='button';b.textContent='Gerar briefing visual';b.setAttribute('aria-label','Gerar briefing visual meteorológico do CIM');share.insertAdjacentElement('afterend',b);b.onclick=show}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();