const CIM={lat:-3.845481,lon:-38.460447,runwayLength:230,runwayWidth:12,runwayTrueHeading:109.8,runwayEnds:[{name:'13',magnetic:130,trueHeading:109.8},{name:'31',magnetic:310,trueHeading:289.8}],timezone:'America/Fortaleza',regRadius:300,pilotOffset:38};
const CARTO_KEY='cb1_2mwu_1_8f33f90d0126a08fc2b8abf2';
let lastWindModelDate=null;
function normalize(a){return((a%360)+360)%360}
function signedAngle(a,b){let d=normalize(a-b);if(d>180)d-=360;return d}
function compass(deg){const p=['N','NNE','NE','ENE','L','ESE','SE','SSE','S','SSO','SO','OSO','O','ONO','NO','NNO'];return p[Math.round(normalize(deg)/22.5)%16]}
function fmtTime(v){const d=v instanceof Date?v:new Date(v);if(Number.isNaN(d.getTime()))return'--:--';return new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:CIM.timezone}).format(d)}
function ageMinutes(d){return !d||Number.isNaN(d.getTime())?Infinity:Math.max(0,(Date.now()-d.getTime())/60000)}
function openMeteoDate(value,offsetSeconds){if(!value)return null;if(/[zZ]$|[+-]\d\d:\d\d$/.test(value)){const d=new Date(value);return Number.isNaN(d.getTime())?null:d}const m=String(value).match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})(?::(\d{2}))?$/);if(!m)return null;return new Date(Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+(m[6]||0))-(Number(offsetSeconds)||0)*1000)}
function clock(){const n=new Date();document.querySelector('#clock').textContent=new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:CIM.timezone}).format(n);document.querySelector('#date').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',timeZone:CIM.timezone}).format(n)}
function runwayAnalysis(direction,speed){return CIM.runwayEnds.map(r=>{const delta=signedAngle(direction,r.trueHeading);return{...r,delta,head:speed*Math.cos(delta*Math.PI/180),cross:speed*Math.sin(delta*Math.PI/180)}}).sort((a,b)=>b.head-a.head)[0]}
function classify(a,gust){const cross=Math.abs(a.cross);if(gust>45||cross>25)return['bad','Vento desfavorável'];if(gust>35||cross>20)return['challenging','Vento desafiador'];if(gust>25||cross>12)return['caution','Atenção ao vento'];return['good','Vento favorável']}
function angleLabel(v){const a=Math.abs(v);if(a<10)return'quase alinhado';if(a<30)return'levemente cruzado';if(a<60)return'cruzado';return'fortemente cruzado'}
function destination(lat,lon,bearing,distance){const R=6378137,δ=distance/R,θ=bearing*Math.PI/180,φ1=lat*Math.PI/180,λ1=lon*Math.PI/180;const φ2=Math.asin(Math.sin(φ1)*Math.cos(δ)+Math.cos(φ1)*Math.sin(δ)*Math.cos(θ));const λ2=λ1+Math.atan2(Math.sin(θ)*Math.sin(δ)*Math.cos(φ1),Math.cos(δ)-Math.sin(φ1)*Math.sin(φ2));return[φ2*180/Math.PI,λ2*180/Math.PI]}
function render(data){
 const c=data.current,h=data.hourly,offset=data.utc_offset_seconds||0;const modelDate=openMeteoDate(c.time,offset)||new Date();lastWindModelDate=modelDate;const age=ageMinutes(modelDate);const a=runwayAnalysis(c.wind_direction_10m,c.wind_speed_10m);const [level,label]=classify(a,c.wind_gusts_10m||0);const pill=document.querySelector('#operation-pill');pill.className='operation-pill '+(age>45?'caution':level);pill.querySelector('strong').textContent=age>45?'Vento desatualizado':label;
 document.querySelector('#preferred-runway').textContent=a.name;document.querySelector('#runway-reason').textContent=`Cabeceira ${a.name} oferece ${Math.abs(a.head).toFixed(1)} km/h de ${a.head>=0?'vento de proa':'vento de cauda'} segundo o intervalo atual do modelo.`;document.querySelector('#wind').textContent=`${Math.round(c.wind_speed_10m)} km/h`;document.querySelector('#wind-dir').textContent=`${Math.round(c.wind_direction_10m)}° ${compass(c.wind_direction_10m)}`;document.querySelector('#gust').textContent=`${Math.round(c.wind_gusts_10m)} km/h`;document.querySelector('#gust-delta').textContent=`+${Math.max(0,Math.round(c.wind_gusts_10m-c.wind_speed_10m))} km/h sobre o vento médio`;document.querySelector('#headwind').textContent=`${Math.abs(a.head).toFixed(1)} km/h`;document.querySelector('#headwind-label').textContent=a.head>=0?'de proa':'de cauda';document.querySelector('#crosswind').textContent=`${Math.abs(a.cross).toFixed(1)} km/h`;document.querySelector('#crosswind-side').textContent=Math.abs(a.cross)<.5?'praticamente sem través':a.cross>0?'da direita para a esquerda':'da esquerda para a direita';document.querySelector('#relative-angle').textContent=`${Math.abs(a.delta).toFixed(0)}°`;document.querySelector('#angle-label').textContent=angleLabel(a.delta);
 const rotation=normalize(Number(c.wind_direction_10m)+90);const vector=document.querySelector('#wind-vector');vector.style.transform=`rotate(${rotation}deg)`;vector.style.setProperty('--wind-label-counter',`${-rotation}deg`);vector.title=`Vento de ${Math.round(c.wind_direction_10m)}°; seta mostra para onde o ar se desloca`;document.querySelector('#wind-vector-label').textContent=`${Math.round(c.wind_speed_10m)} km/h`;document.querySelector('#updated').textContent=`Modelo válido ${fmtTime(modelDate)}${age>45?' · ATRASADO':''}`;
 const now=new Date();const cards=[];for(let i=0;i<h.time.length&&cards.length<10;i++){const t=openMeteoDate(h.time[i],offset);if(t&&t>=now){const ra=runwayAnalysis(h.wind_direction_10m[i],h.wind_speed_10m[i]);cards.push(`<article class="trend-card"><strong>${fmtTime(t)}</strong><span class="rw">PISTA ${ra.name}</span><small>Vento ${Math.round(h.wind_speed_10m[i])} km/h<br>${Math.round(h.wind_direction_10m[i])}° ${compass(h.wind_direction_10m[i])}<br>Raj. ${Math.round(h.wind_gusts_10m[i])} km/h<br>Través ${Math.abs(ra.cross).toFixed(1)} km/h</small></article>`)}}document.querySelector('#trend').innerHTML=cards.join('')
}
function initMap(){
 const el=document.querySelector('#flight-map');if(!el||typeof L==='undefined')return;
 const center=[CIM.lat,CIM.lon];
 const map=L.map(el,{zoomControl:true,attributionControl:true}).setView(center,15);
 const carto=L.tileLayer(`https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png?key=${CARTO_KEY}`,{subdomains:'abcd',maxZoom:20,attribution:'&copy; OpenStreetMap contributors, &copy; CARTO'}).addTo(map);
 const fallback=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'});
 let fallbackActivated=false;carto.on('tileerror',()=>{if(!fallbackActivated){fallbackActivated=true;map.removeLayer(carto);fallback.addTo(map)}});
 function off(origin,forward,right){let p=destination(origin[0],origin[1],CIM.runwayTrueHeading,forward);return destination(p[0],p[1],CIM.runwayTrueHeading+90,right)}
 function badge(text,bg='#0b1d2b',fg='#fff'){return L.divIcon({className:'map-badge-wrap',html:`<div class="map-badge" style="background:${bg};color:${fg}">${text}</div>`,iconSize:[46,32],iconAnchor:[23,16]})}
 function measureBadge(text){return L.divIcon({className:'map-badge-wrap',html:`<div class="map-badge" style="background:#fff;color:#0f3f9e;border:1px solid #2563eb;white-space:nowrap">${text}</div>`,iconSize:[96,30],iconAnchor:[48,15]})}
 const halfL=CIM.runwayLength/2;const th13=off(center,-halfL,0),th31=off(center,halfL,0);
 L.marker(th13,{icon:badge('13')}).addTo(map).bindTooltip('Cabeceira 13 · posição indicativa');L.marker(th31,{icon:badge('31')}).addTo(map).bindTooltip('Cabeceira 31 · posição indicativa');
 const pilot=off(center,0,CIM.pilotOffset);const pilotLineA=destination(pilot[0],pilot[1],CIM.runwayTrueHeading,340),pilotLineB=destination(pilot[0],pilot[1],CIM.runwayTrueHeading+180,340);
 L.polyline([pilotLineA,pilotLineB],{color:'#f4b942',weight:4,dashArray:'10 7'}).addTo(map).bindTooltip('LINHA DOS PILOTOS · posição aproximada no mapa');L.circleMarker(pilot,{radius:8,color:'#7c4a03',weight:2,fillColor:'#f4b942',fillOpacity:1}).addTo(map);L.marker(pilot,{icon:badge('PILOTO','#f4b942','#07131f')}).addTo(map).bindTooltip('Posição de referência aproximada; falta coordenada medida da linha real');
 const outer=L.circle(pilot,{radius:CIM.regRadius,color:'#2563eb',weight:3,dashArray:'11 8',fill:false}).addTo(map).bindTooltip('REFERÊNCIA HORIZONTAL GERAL · raio 300 m a partir do piloto · diâmetro 600 m');
 function sector(startBearing,endBearing){const pts=[pilot];for(let b=startBearing;b<=endBearing;b+=5)pts.push(destination(pilot[0],pilot[1],normalize(b),CIM.regRadius));pts.push(destination(pilot[0],pilot[1],normalize(endBearing),CIM.regRadius));return pts}
 const allowedStart=CIM.runwayTrueHeading+180,allowedEnd=CIM.runwayTrueHeading+360,forbiddenStart=CIM.runwayTrueHeading,forbiddenEnd=CIM.runwayTrueHeading+180;
 L.polygon(sector(allowedStart,allowedEnd),{color:'#2563eb',weight:1,fillColor:'#3b82f6',fillOpacity:.14}).addTo(map).bindTooltip('SETOR DE VOO · lado da lagoa · regra operacional CIM aplicada dentro da referência de 300 m');L.polygon(sector(forbiddenStart,forbiddenEnd),{color:'#dc2626',weight:1,fillColor:'#ef4444',fillOpacity:.15}).addTo(map).bindTooltip('NÃO VOAR · atrás dos pilotos · regra CIM');
 const allowedBearing=CIM.runwayTrueHeading-90,forbiddenBearing=CIM.runwayTrueHeading+90;const allowedLabel=destination(pilot[0],pilot[1],allowedBearing,175),forbiddenLabel=destination(pilot[0],pilot[1],forbiddenBearing,175);
 L.marker(allowedLabel,{icon:L.divIcon({className:'map-zone-wrap',html:'<div class="map-zone allowed"><strong>SETOR DE VOO</strong><span>LADO DA LAGOA · até 300 m</span></div>',iconSize:[160,52],iconAnchor:[80,26]})}).addTo(map);L.marker(forbiddenLabel,{icon:L.divIcon({className:'map-zone-wrap',html:'<div class="map-zone forbidden"><strong>NÃO VOAR</strong><span>atrás dos pilotos · regra CIM</span></div>',iconSize:[160,52],iconAnchor:[80,26]})}).addTo(map);
 const radiusEnd=destination(pilot[0],pilot[1],allowedBearing,CIM.regRadius),radiusMid=destination(pilot[0],pilot[1],allowedBearing,CIM.regRadius/2);L.polyline([pilot,radiusEnd],{color:'#2563eb',weight:2,dashArray:'4 5',opacity:.85,interactive:false}).addTo(map);L.marker(radiusMid,{icon:measureBadge('RAIO 300 m'),interactive:false}).addTo(map);
 map.fitBounds(outer.getBounds().pad(.14));L.control.scale({imperial:false,maxWidth:160}).addTo(map);setTimeout(()=>map.invalidateSize(),150);window.addEventListener('resize',()=>map.invalidateSize());
}
async function load(){const p=new URLSearchParams({latitude:CIM.lat,longitude:CIM.lon,timezone:CIM.timezone,current:'wind_speed_10m,wind_direction_10m,wind_gusts_10m',hourly:'wind_speed_10m,wind_direction_10m,wind_gusts_10m'});try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?${p}&_=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error();render(await r.json())}catch{const pill=document.querySelector('#operation-pill');pill.className='operation-pill bad';pill.querySelector('strong').textContent='Vento indisponível';document.querySelector('#updated').textContent='Falha na consulta do modelo'}}
function windWatchdog(){if(!lastWindModelDate||ageMinutes(lastWindModelDate)<=45)return;const pill=document.querySelector('#operation-pill');pill.className='operation-pill caution';pill.querySelector('strong').textContent='Vento desatualizado';document.querySelector('#updated').textContent=`Modelo de ${fmtTime(lastWindModelDate)} · ATRASADO`}
clock();setInterval(clock,1000);initMap();load();setInterval(load,5*60*1000);setInterval(windWatchdog,60*1000);
