const CIM={lat:-3.8455,lon:-38.4596,runways:[130,310],length:230,width:12,timezone:'America/Fortaleza'};
function normalize(a){return((a%360)+360)%360}
function signedAngle(a,b){let d=normalize(a-b);if(d>180)d-=360;return d}
function compass(deg){const p=['N','NNE','NE','ENE','L','ESE','SE','SSE','S','SSO','SO','OSO','O','ONO','NO','NNO'];return p[Math.round(normalize(deg)/22.5)%16]}
function fmtTime(v){return new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:CIM.timezone}).format(new Date(v))}
function clock(){const n=new Date();document.querySelector('#clock').textContent=new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:CIM.timezone}).format(n);document.querySelector('#date').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',timeZone:CIM.timezone}).format(n)}
function runwayAnalysis(direction,speed){const list=CIM.runways.map(runway=>{const delta=signedAngle(direction,runway);return{runway,delta,head:speed*Math.cos(delta*Math.PI/180),cross:speed*Math.sin(delta*Math.PI/180)}}).sort((a,b)=>b.head-a.head);return list[0]}
function classify(a,gust){const cross=Math.abs(a.cross);if(gust>35||cross>20)return['bad','Condição desfavorável'];if(gust>25||cross>12)return['caution','Atenção ao vento'];return['good','Condição favorável']}
function angleLabel(v){const a=Math.abs(v);if(a<10)return'quase alinhado';if(a<30)return'levemente cruzado';if(a<60)return'cruzado';return'fortemente cruzado'}
function render(data){const c=data.current,h=data.hourly;const a=runwayAnalysis(c.wind_direction_10m,c.wind_speed_10m);const [level,label]=classify(a,c.wind_gusts_10m||0);const pill=document.querySelector('#operation-pill');pill.className='operation-pill '+level;pill.querySelector('strong').textContent=label;
 document.querySelector('#preferred-runway').textContent=a.runway===130?'13':'31';document.querySelector('#runway-reason').textContent=`Cabeceira ${a.runway===130?'13':'31'} oferece ${Math.abs(a.head).toFixed(1)} km/h de ${a.head>=0?'vento de proa':'vento de cauda'} com o vento atual.`;
 document.querySelector('#wind').textContent=`${Math.round(c.wind_speed_10m)} km/h`;document.querySelector('#wind-dir').textContent=`${Math.round(c.wind_direction_10m)}° ${compass(c.wind_direction_10m)}`;document.querySelector('#gust').textContent=`${Math.round(c.wind_gusts_10m)} km/h`;document.querySelector('#gust-delta').textContent=`+${Math.max(0,Math.round(c.wind_gusts_10m-c.wind_speed_10m))} km/h sobre o vento médio`;document.querySelector('#headwind').textContent=`${Math.abs(a.head).toFixed(1)} km/h`;document.querySelector('#headwind-label').textContent=a.head>=0?'de proa':'de cauda';document.querySelector('#crosswind').textContent=`${Math.abs(a.cross).toFixed(1)} km/h`;document.querySelector('#crosswind-side').textContent=Math.abs(a.cross)<.5?'praticamente sem través':a.cross>0?'da esquerda para a direita':'da direita para a esquerda';document.querySelector('#relative-angle').textContent=`${Math.abs(a.delta).toFixed(0)}°`;document.querySelector('#angle-label').textContent=angleLabel(a.delta);
 document.querySelector('#wind-vector').style.transform=`rotate(${c.wind_direction_10m}deg)`;document.querySelector('#wind-vector-label').textContent=`${Math.round(c.wind_speed_10m)} km/h`;document.querySelector('#updated').textContent=`Atualizado ${fmtTime(c.time)}`;
 const now=new Date();const cards=[];for(let i=0;i<h.time.length&&cards.length<10;i++){const t=new Date(h.time[i]);if(t>=now){const ra=runwayAnalysis(h.wind_direction_10m[i],h.wind_speed_10m[i]);cards.push(`<article class="trend-card"><strong>${cards.length===0?'Agora':fmtTime(h.time[i])}</strong><span class="rw">PISTA ${ra.runway===130?'13':'31'}</span><small>Vento ${Math.round(h.wind_speed_10m[i])} km/h<br>${Math.round(h.wind_direction_10m[i])}° ${compass(h.wind_direction_10m[i])}<br>Raj. ${Math.round(h.wind_gusts_10m[i])} km/h<br>Través ${Math.abs(ra.cross).toFixed(1)} km/h</small></article>`)}}document.querySelector('#trend').innerHTML=cards.join('')}
async function load(){const p=new URLSearchParams({latitude:CIM.lat,longitude:CIM.lon,timezone:CIM.timezone,current:'wind_speed_10m,wind_direction_10m,wind_gusts_10m',hourly:'wind_speed_10m,wind_direction_10m,wind_gusts_10m'});try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?${p}`);if(!r.ok)throw Error();render(await r.json())}catch{const pill=document.querySelector('#operation-pill');pill.className='operation-pill bad';pill.querySelector('strong').textContent='Falha ao consultar vento'}}
clock();setInterval(clock,1000);load();setInterval(load,15*60*1000);